### ISSUE TITLE
how and when to use OUTPUT_ENABLE_GROUP in pin assignment

### ISSUE THREAD

**Issue by tracyone** [adrianj/RangeImaging#4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP "1743998284" -to ${::ppl_instance_name}mem_dq[0]

does mem_dq is write only in your application?

**Comment by adrianj** [comment]
To which file are you referring?  That piece of script looks to me like it was auto-generated by the Altera tools.

To answer your question, 'mem_dq' is the set of data lines to the RAM chip. They are both read and write.  In the top level design they are referred to as ddr2_devX_dq (X = a or b).
